import {readFileSync} from 'node:fs';
import {publication} from '../../src/data/published/catalogue.ts';
import {digest} from './records.ts';
import {validateCatalogue} from './validate.ts';
import {snapshotText} from './operations.ts';
validateCatalogue(publication.data);
if(publication.schemaVersion!==1||digest(publication.data)!==publication.revision)throw new Error('Publication integrity mismatch');
if(publication.data.entries.some(e=>!['REVIEWED','VERIFIED'].includes(e.verificationState))||publication.data.variants.some(v=>!['REVIEWED','VERIFIED'].includes(v.verificationState)))throw new Error('Unreviewed publication');
if(readFileSync('src/data/published/catalogue.ts','utf8').replaceAll('\r\n','\n')!==snapshotText(publication))throw new Error('Snapshot is not reproducible');
console.log('Verified offline publication',publication.revision);
